const db = require("./db");
const { Campus, Student } = require("./db/models");

const tempStuImgUrl =
  "https://cdn.landesa.org/wp-content/uploads/default-user-image.png";

//Top 3 U.S News College dummy data
const seedCampuses = [
  {
    name: "Princeton University",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Nassau_Hall_Princeton.JPG",
    address: "Princeton, NJ 08544 USA",
    description:
      "Princeton is an independent, coeducational, nondenominational institution that provides undergraduate and graduate instruction in the humanities, social sciences, natural sciences, and engineering.",
  },
  {
    name: "Harvard University",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/11/Sanders_theater_2009y.JPG",
    address: "Massachusetts Hall, Cambridge, MA 02138",
    description:
      "Harvard University, located in Cambridge, Massachusetts, is a world-renowned Ivy League institution recognized for its exceptional academics and intellectual rigor. With a rich history dating back to 1636, Harvard offers a diverse range of programs and attracts top students and scholars from around the globe.",
  },
  {
    name: "Columbia University",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/63/Columbia_University_College_Walk_Court_Yard_06.JPG",
    address: "116th and Broadway, New York, NY 10027",
    description:
      "Columbia University is one of the world's most important centers of research and at the same time a distinctive and distinguished learning environment for undergraduates and graduate students in many scholarly and professional fields. The University recognizes the importance of its location in New York City and seeks to link its research and teaching to the vast resources of a great metropolis. ",
  },
];

//Dummy data generated by chatGPT
const seedStudents = [
  {
    firstName: "Olivia",
    lastName: "Anderson",
    email: "olivia.anderson@gmail.com",
    imgUrl: tempStuImgUrl,
    gpa: 3.9,
  },
  {
    firstName: "Benjamin",
    lastName: "Thompson",
    email: "benjamin.thompson@gmail.com",
    imgUrl: tempStuImgUrl,
    gpa: 3.5,
  },
  {
    firstName: "Sophia",
    lastName: "Rodriguez",
    email: "sophia.rodriguez@gmail.com",
    imgUrl: tempStuImgUrl,
    gpa: 3.7,
  },
  {
    firstName: "Liam",
    lastName: "Walker",
    email: "liam.walker@gmail.com",
    imgUrl: tempStuImgUrl,
    gpa: 3.2,
  },
  {
    firstName: "Emma",
    lastName: "Collins",
    email: "emma.collins@gmail.com",
    imgUrl: tempStuImgUrl,
    gpa: 3.8,
  },
];

const seed = async () => {
  await Campus.bulkCreate(seedCampuses);
  await Student.bulkCreate(seedStudents);
};

seed().then(() => process.exit());
